# Generated by Django 5.1.1 on 2024-10-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(default="Country", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="district",
            field=models.CharField(default="District", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(default="State", max_length=100),
        ),
    ]
