# Generated by Django 5.1.1 on 2024-10-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_rated",
            field=models.BooleanField(default=False),
        ),
    ]
