# Generated by Django 5.1.1 on 2024-10-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_course_is_rated"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_rating", models.IntegerField(default=0)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manager.chapter",
                    ),
                ),
            ],
        ),
    ]
