# Generated by Django 5.1.1 on 2024-10-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_chapterrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterrating",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
